<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShipCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipCategoryRepository extends EntityRepository
{
    public function getAllWithShip(){
        $query = $this->createQueryBuilder('c')
            ->select('c')
            ->leftJoin('AppBundle:Ship','s','WITH','s.category = c.id')
            ->groupBy('c.name')
            ->addSelect('COUNT(s)')
            ->getQuery();

        return $result = $query->getResult();
    }
}
