<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipRepository extends EntityRepository
{
    public function countNbCatAvailable($cat){
        $query = $this->createQueryBuilder('ship')
                ->select('COUNT(ship)')
                ->where('ship.category = :category')
                ->andWhere('ship.available = true')
                ->setParameter(':category',$cat)
                ->getQuery();
        return $query->getSingleScalarResult();
    }

    public function countNbCat($cat){
        $query = $this->createQueryBuilder('ship')
            ->select('COUNT(ship)')
            ->where('ship.category = :category')
            ->setParameter(':category',$cat)
            ->getQuery();
        return $query->getSingleScalarResult();
    }
}
